apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: address-classifier
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "iamma00/address-classifier:v1"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/src/classify.py
  sparkVersion: 3.5.1
  driver:
    cores: 1
    coreRequest: "300m"
    memory: 512m
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: address-data
        mountPath: /data
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: password
  executor:
    cores: 1
    coreRequest: "300m"
    instances: 2
    memory: 512m
    volumeMounts:
      - name: address-data
        mountPath: /data
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-creds
            key: password
  volumes:
    - name: address-data
      persistentVolumeClaim:
        claimName: address-data-pvc
